spring:    
 datasource:
   url: jdbc:h2:mem:localhost/myDB
   username: 
   password:   
 h2:
   console:
     enabled: true         
 jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.H2Dialect
       show_sql: true
       ddl-auto: create-drop       
logging:
  level:
    org.springframework: ERROR
    com.com.lucianoortizsilva.paginacao: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log